* European Bottlecaps
In 2018 the European Parliament initiated the process to regulate bottlecaps for plastic bottles with volume under 3L. The regulation went into effect in 2024. It enumerates a functional requirement that bottlecaps shall remain attached to the bottles. For a primer, read https://www.corvaglia.com/tethered-caps/.

The new European bottlecaps have four practical downsides:
1. The bottlecap has the potential to get in the way, so it requires cognitive load when opening to first observe the resulting orientation and then decide the appropriate course of action. Opening and drinking or pouring from a bottle shouldn't require this type of cognitive load (see 2 and 3 for examples of added cognitive load).
2. When drinking from the bottle directly they get in your face, which is unpleasant due to the sharp plastic edges of the bottlecap. The course of action to avoid this is to rotate the bottle or rotate the cap. This means using your other hand, unless you feel comfortable rotating the bottle with one hand.
3. When pouring from the bottle, if the bottlecap attachment ring is loose, the bottlecap rotates due to gravity and gets right in the way of the liquid being poured. So you must hold it aside with another hand.
4. Sometimes they require more force to open.

The new European bottlecap is associated with 4 moral downsides:
1. Government overreach: no inter-national governing body should be able to decide functional requirements for something as trivial bottlecap for member countries.
2. Useless purpose: I can hardly imagine how keeping bottlecaps attached to bottles with help the environment. Even if it helps a tiny bit, it's still effectively useless with respect to policies such as a carbon tax.
3. Negative effect for the people: the bottlecaps are badly designed and make quality of life worse.
4. Government overreach combined with a useless purpose as well as with negative effect for the people: moral downsides 2 and 3 make the government overreach even worse.

