#+title: European Tethered Bottlecaps

In 2018 the European Parliament initiated the process to regulate bottlecaps for plastic bottles with volume under 3L. The regulation went into effect in 2024. It enumerates a functional requirement that bottlecaps shall remain attached to the bottles. For a primer, read https://www.corvaglia.com/tethered-caps/.

The new European bottlecaps have four practical downsides:
1. The bottlecaps are unpleasant when drinking from the bottle directly because they get in your face and have sharp plastic edges.
2. The bottlecaps can get in the way of the liquid being poured if its attachment ring is loose, because then the cap rotates due to gravity. 
3. The bottlecap requires cognitive load when opening to ensure it doesn't become an obstacle to the liquid being poured, as in (2). The user must first observe the orientation of the fully unscrewed cap and then decide the appropriate course of action. If it's loose, the user must use his other hand to hold the loose cap aside. Opening and drinking or pouring from a bottle shouldn't require this type of cognitive load.
4. Sometimes they require more force to open.
5. After opening and closing a couple of times one leg of the attachment ring breaks, leaving the cap dangling. This makes (1) and (3) worse.
6. Some cap designs are harder to screw back on because you have to jam them on diagonally first given their tether joint.

The new European bottlecap is associated with 4 moral downsides:
1. Government overreach: no inter-national governing body should be able to decide functional requirements for something as trivial as bottlecaps for member countries. I can understand deciding functional requirements for non-trivial devices like electrical outlets or vehicles. But a bottlecap is too trivial. An international government who can regulate bottlecaps has too much power.
2. Useless purpose: I can hardly imagine how keeping bottlecaps attached to bottles with help the environment. Even if it helps a tiny bit, it's still effectively useless with respect to policies such as a carbon tax.
3. Negative effect for the people: the bottlecaps are badly designed and make quality of life worse.
4. Government overreach combined with a useless purpose as well as with negative effect for the people: moral downsides 2 and 3 make the government overreach even worse than plain overreach.

