#+title: Pre-Concept

These are raw ideas which may later enter the Concept stage.
* Software
1. When3Meet (When2Meet Alternative): When2Meet needs several features (and it makes sense to name an updated version When3Meet):
   - option to invert already selected times if dragging over them as part of another time selection
   - ability to leave notes about (un)availability in specific future weeks, ideally as granular as each 15 minute slot
   - ability to remove people from a group after creation
   - ability change days in schedule after creation
   - slightly more modern UI
2. Digital Lab Notebooks backed by Git and public-key cryptography
   _Problem:_ lab notebooks are essential research tools. They track experimental procedure and implemented sequence, lab notes, and the genesis of creative ideas. Writing on paper, however, even in non-erasable ink, does not provide any integrity to the data and metadata that lab notebooks must track. A written note can be altered after-the-fact, providing no assurance as to the chronology of the lab notes or their data integrity.

   _Solution:_ use a digital lab notebook with Git to track chronology and preserve integrity as well as GPG to provide a second layer of assurance, proof of digital notebook ownership, and privacy and security via encryption.

   _Implementation:_ a program manages your lab notebooks starting with a root directory, which contains =notebooks=. Each =notebook= is its own Git repo and receives its own digital signatures. Users can decide the semantics of a =notebook=, for example whether one notebook corresponds to one laboratory, to one day of work, to one lab session, to one lab assistant. These can of course be mixed and matched and do not affect how the program works. All the program does is track each notebook with Git and GPG.

   If a user keeps a hand-written lab notebook, then the program can use photos of the pages as evidence. They could be OCRed to provide basic search functionality.
3. App to run a bunch of ROS2 commands in a certain sequence.
4. Computer app to flash the screen if you haven't blinked in a certain time threshold.
5. Website which takes a photo of your sketch and tells you the axonometric view (isometric, trimetric, or dimetric). If your sketch is somewhere in between, the website reports the values of the angles which define your view, and how close you are to each axonometric view.
6. Weather report service which tells you the weather along a vehicle trajectory. So you know when it'll rain or not along your 6 hour drive.
7. Website which finds you locations to live which have specific types of weather patterns, e.g. 50% sunny, 25% rainy, above 70F.
* Electronic
1. TRRS Cable Tester
2. USB Info Dongle: sits between your computer (just for power) and a USB stick, and has a tiny screen which displays USB info, including: partitions, filesystems, size (used, available, unallocated), as well as any ISOs that might be flashed
* Mechanical
1. PB&J Bread Mold: a mold to make slices of bread with walls. These would hold in the PB&J better and prevent it from spilling out the sides.
2. Constant force stirring spoon
3. Baking soda dispenser
4. Pneumatic device for clearing used grounds from Moka espresso pot funnel
5. Wearable laptop tray: straps on to your belly and holds a small, light computer for on the go hacking.
6. Cup whose shape is optimized for receiving water quickly with minimal to no splahes.
7. Bork: the bone fork. A kitchen utensil that grasps onto bones to let you eat the remaining meat off the bone without getting your hands dirty. Great for ribs, chicken wings, etc.
8. Deluxe movie theater popcorn holder.
   1. Fits into theater seat cupholder so you don't have to hold it yourself.
   2. Extends sideways left and right so you and your friend can both enjoy without passing back and forth.
   3. Has a grate and collection chamber at the bottom which collects unpopped kernels.
   4. Dishwashable so you can add butter without worry.
   5. Has lid so you can toss with salt.
   6. Microwavable.
   7. Cardboard single-use version.
9. Food dispensers shaped like fire extinguishers.
   1. Whipped cream.
   2. Olive oil.
   3. Salt, pepper.
* Mechatronic
1. Autonomous kitchen stirrer. Constant force. Two-axis gantry with arm.
2. Autonomous pancake stacker with butter and syrup placement.
3. Autonomous egg poacher.
4. Universal BIOS button. Spams F11, F12, Delete, etc for you.
5. Luxury Smart Umbrella
   1. High build quality: no more
      1. Tight tolerances
      2. High rigidty and lightweight materials
   2. Hand warmer in the handle
   3. Lights to illuminate the ground
   4. Dynamically extensible umbrella rim for better rain cover
   5. Safety mechanisms to control or reduce risk of wind damage
      1. Warning if stress on umbrella exceeds limit
   6. Motorized opening and closing?
   7. Heads-up display on umbrella interior with maps navigation
   8. Integrated path planning which optimizes for most natural rain cover (under trees, awnings) (this would probably require a huge satellite image dataset)
   9. Haptic feedback which indicates if the umbrella should be oriented at an angle to provide better rain cover. If rain is a vector field, sensors must measure the surface average of the vector field through the surface of the umbrella. The haptic feedback then must communicate the angle between the surface average vector and the umbrella's normal vector.
6. The best suitcase.
   1. Wheels with user-controlled active suspension. This way if you take a corner while running in the airport, you can use the active suspension to keep both wheels on the ground.
   2. Retractable wheels.
   3. Off-road wheels, suitable at least for gravel and cobblestone roads.
   4. Wheels that don't break over time and can be dropped down a staircase. Probably rubber wheels? Not plastic or pneumatic.
   5. Stands upright on its own.
   6. Hard shell.
   7. Robust handle that doesn't wiggle. Metal + tighter tolerances?
7. Keyboard for common Linux commands for a much more declarative shell experience.
8. Kitchen utensil cleaner. You use a fork, stick it in the cleaner, and it's washed and dried within a few minutes.
9. Smart globe. A globe that rotates and zooms in on the country you're looking at. No rotating with your hands.
10. Car device which makes a hurt sound ("Oof!", "Ouch!", "Ow!") when you go over a bad bump.
* Food
1. Dipping Integrity Score
