* Blog

** Writing
*** Formatting
**** How To Format Units
Italics, spacing, and plurality.
**** Fix Your Dangling Paragraphs
*** Get Rid Of...
**** Extra Words
**** Backslashes
**** Clichés
**** Filler Words
** The Significance of Significant Figures
In the wild I've come to see three categories of sigfig usage:
1. No awareness: the author reports values exactly as they were calculated (usually this means to two decimal places) with no regard to context.
2. Apparent awareness: the author appears to have some awareness of sig figs, but they probably don't have a substantive understanding of why. While decimals are usually not reported, you can tell they lack substantive understanding because they'll still report unnecessary digits with respect to the context (usually the ones digits remains included).
3. Full awareness: the author reports sig figs correctly and prefixes values to emphasize they are approximated (e.g. 10258 in a relevant range of 0 to 100000 -> "about 10000").

You should report sig figs correctly, i.e. with full awareness. To do so you must determine the context of the reported value. As far as I have come up with, this means determining:
1. The potential range of your reported value.
2. The resolution necessary to achieve your goal with the value.

_Example 1: Politician's Approval Rating_
The range is 0-100%. The necessary resolution depends on the goal. If the goal is to give a lay-TV audience a picture of a politician's standing among the people, probably a 5% resolution is necessary, so reporting values as about 30%, about 35%, about 40%, etc is necessary. If the goal is for a napkin math computation of the percent of the popular vote the politician may receive, probably a 1% resolution is necessary. If the goal is a rigorous computation for a professional pollster, probably a hundredths of a % resolution is necessary.

_Example 2: Exam Scores_
The range is 0-100 (assume no extra credit). Assume the goal is to compute the class average for your own analysis of how the class is doing. Then probably a 1% resolution is necessary. Assume the average will be used by students to determine their standing relative to classmates. Now we need additional information to determine the context. Namely, we need the range of actual scores, because 1% resolution may not be precise enough to provide meaningful information about relative standing. This would be the case, for example, if the range of scores is between 90 and 91. Let's say the average is 90 (e.g. 90.4, rounded down). Then we have two problems wrto. relative standing: 1) students who got between 90 and the true average (90.4) will think they did better than the reported average (90), even though they actually did worse; 2) distinctions on the scale of tenths or hundredths of points, out of 100, are not useful for comparing relative standing: if you got a 90.5 and I got a 90.6, an average reported to 1% resolution (90) doesn't really help us determine who did better. You will have done 0.555% better than average, and I will have done 0.666% better than average, or 20% better than you. Whereas with the true average (90.4), you will have done only 0.111% better and I will have done 0.221% better, or 100% better than you.

Let's say that the range of actual scores is 0 to 100. Then probably a 5% resolution is necessary. If the range is 80 to 100, probably a 1% resolution is necessary. If the range is 80 to 85, probably a tenths or hundredths resolution is necessary.

_Example 3: Vehicle Wheelbase_
Now we must deal not only with range and resolution with but the contextual relevance of different units. The range is not set by definition, but by empirical data is probably between 2.5m and 3m. Assume the goal is a rough computation of the longitudinal coordinate of the vehicle's center of mass. Then probably a resolution down to the cm is good enough. If we want a rigorous computation, then probably a resolution down to the mm is good enough. However, should we report the value in mm using units of m, cm, or mm? For example, a wheelbase of 2840mm could be conceivably reported as 2.840m, 2.84m, 284.0cm, 284cm, and 2840mm (these are conceivable insofar as no rounding occurs). Using mm puts the reader in a rigorous mindset, and using m or cm down to mm precision can introduce confusion as to whether we have approximate the left sig fig, so mm is probably necessary.

_Example 4: Huge Numbers_
For huge numbers you can probably drop lots of sig figs because they contribute so little at the large order of magnitude. For example, let's say you do some math and determine that there's 1.0232792349 mol of stars in the universe. A mol is huge, so although you may really want to show your exact value as proof of your rigorous approach, you should probably just report the value as "1 mol" (or 10^23). That extra 4.327...% of a mol, while large (~10^21), isn't really useful for communicating the sheer size. A mol is so huge already that adding 10^21 won't affect our mental representation of the quantity.

_When to prefix "about"?_
If you've altered the value enough that it's fairly different from the original. I'd prefix about in the following cases taken from the examples:
1. Approval rating of 43.4% with a goal of informing the audience about the politician's standing relative to a particularly important mark of 47% approval rating. Report as "about 40%", because 43% is closer to 40% than it is to 47%, even though if we rounded 43% to 45%, then the rounded value (45%) would be closer to 47% than to 43%.
2. True average of 72.45. Report as "about 70" by simple rounding.
3. Vehicle wheelbase of 2840mm reported in m. Report as "about 2.8m" because even though we may be using m in a scenario where a casual approximation is suitable, it's good to emphasize that the value is approximate because those extra 40mm do matter.
** Optimizing Humanities for Engineers
** Don't Call Your FOSS Project Something Unprofessional
Please don't call your FOSS tools something unprofessional like "Doom Emacs". Note that I am a Doom Emacs user. However, I don't want my Professors wondering why some app on my screen has "Doom" in the titlebar.
** Use Your Car's Parking Brake
The parking brake keeps your car exactly where you parked it. The benefits of this include:
- Enhanced safety. Your car won't slip, which can be particularly bad in tight parking spaces or if you must get out of the car just after you park.
- Determinism. The world is already chaotic enough, might as well make it slightly less so.
** Units or Acronyms?
** European Bottlecaps
In 2018 the European Parliament initiated the process to regulate bottlecaps for plastic bottles with volume under 3L. The regulation went into effect in 2024. It enumerates a functional requirement that bottlecaps shall remain attached to the bottles. For a primer, read https://www.corvaglia.com/tethered-caps/.

The new European bottlecaps have four practical downsides:
1. The bottlecap has the potential to get in the way, so it requires cognitive load when opening to first observe the resulting orientation and then decide the appropriate course of action. Opening and drinking or pouring from a bottle shouldn't require this type of cognitive load (see 2 and 3 for examples of added cognitive load).
2. When drinking from the bottle directly they get in your face, which is unpleasant due to the sharp plastic edges of the bottlecap. The course of action to avoid this is to rotate the bottle or rotate the cap. This means using your other hand, unless you feel comfortable rotating the bottle with one hand.
3. When pouring from the bottle, if the bottlecap attachment ring is loose, the bottlecap rotates due to gravity and gets right in the way of the liquid being poured. So you must hold it aside with another hand.
4. Sometimes they require more force to open.

The new European bottlecap is associated with X moral downsides:
1. Government overreach: no inter-national governing body should be able to decide functional requirements for something as trivial bottlecap for member countries.
2. Useless purpose: I can hardly imagine how keeping bottlecaps attached to bottles with help the environment. Even if it helps a tiny bit, it's still effectively useless with respect to policies such as a carbon tax.
3. Negative effect for the people: the bottlecaps are badly designed and make quality of life worse.
4. Government overreach combined with a useless purpose as well as with negative effect for the people: moral downsides 2 and 3 make the government overreach even worse.
** Clarifying the Philosophical Foundations of Free Software
** Practical Tips for Staying Calorie Deficits
1. If your calorie limit is <2000, have only two meals. They can be bigger, and will be more psychologically rewarding that three smaller meals. Also, eating a small meal can feel limiting and raises temptations. Three smaller meals only amplifies these feelings, so avoid that by having two bigger ones.
2. If you're doing two meals, use a 1:2 breakfast:dinner calorie ratio. The big dinner will feel rewarding.
3. Low calorie toppings: spices, soy sauce.
4. Don't weigh too often, i.e. once a day. Weighing less often, but seeing a bigger weight drop, is more psychologically rewarding. Twice a week could mean seeing a rewarding 2lb drop each weigh-in (2% loss per week at 200lb).
5. Don't set a limit on eating green vegetables. I don't know the science, but I have a hard time imagining these would cause weight gain, and even slow weight loss. Even if you're doing several hundred calories of greens.
** Safe Driving
*** Quick tips
- Two hands on steering wheel at all times
- Hands on steering wheel at 2 and 10 o'clock positions
- Don't drive much over 60 mph
- Don't drive over 60 mph in the rain
- Stop for a break every 2hrs
- Wait a half second at traffic start events when it's your turn to go
  - e.g. traffic light red -> green
- There's no such thing as too much distance to the car ahead of you
- Maintain a hard minimum distance to the car ahead of you of 1 car length for every 10 mph
- Always assume there's something about to pop out from behind a parked car
- Before going at an intersection where you just got green, wait for incoming cars which just got red to stop, or slow down to <10mph
- Going an extra few mph won't save much time at all, but it will introduce lots more risk, even at slow speeds
  - i.e. no need to go 25mph (vs 15-20mph) in a city, or 75mph (vs 60mph) on the highway
  - The time of a short trip (~ a few miles) is dominated by speed-invariant phenomenon, e.g. number of stop lights, so going 15mph instead of 10mph isn't really helping much
  - The time of a long trip on the highway and on small roads (>10 miles) is dominated by the distance, so a bit more speed saves a bit of time. But, this increase in speed introduces lots of risk: on the highway, 60mph to 70mph is a big risk; on small roads, 30mph to 40mph is a big risk given the frequent twists and turns
- Driving is inherently very risky (though not necessarily statistically dangerous) so there's really no way to guarantee safety, which means you can't get out of these rules
*** Frameworks
**** Perception as an Event Loop
Accurate, consistent, and frequent perception is critical for safe driving. This perception involves lots of data and moderate to high cognitive load. We can improve consistency, increase frequency, and reduce cognitive load by following an event loop as we drive.

The loop:
- Check rearview mirror
- Check left side mirror
- Check right side mirror

Certain events will interrupt our loop, and each event should trigger its own loop:
- Lane change
  - Check all mirrors
  - Check next lane
  - Verify empty blind spot
  - Signal
- Other passing
  - Verify that other car's speed and velocity are nominal
  - Estimate if other car's distance will be too close
  - Verify that distance is enough as the car is passing

More difficult things to add to the loop:
- Track distance to the car behind you (tailgate, moderate, or long)
- Path planning of cars around you
- For each lane left and right of you, maintain binary values for can/cannot do a quick lane change evasive maneuver into that lane
**** Slower = Safer
**** Predict the Paths of Other Vehicles
If you can predict the paths of other vehicles you'll be better prepared to react if something goes wrong with them. This is particularly useful:
- At highway speeds
- When other vehicles switch lanes
- At complex intersections
**** Optimizing Cognitive Load for Long Drives 
Unfortunately, employing all the tips and frameworks described here requires high cognitive effort. This makes long drives difficult (> 15 minutes, in my experience). Thus, we should optimize which tips and frameworks to leave out.
- When there's no pedestrians or other vehicles around, you can ease up on exteroception
- At slow (<20 mph) speeds, you can use less precise path planning and control
- At stop lights you can physically relax
